# Why use array for financial analysis?

Array can handle large datasets efficiently. 

Array using np.array().

In [5]:
import numpy as np

In [16]:
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings_array = np.array(earnings)
prices_array = np.array(prices)

In [18]:
print(earnings_array)
print(type(earnings_array))

[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]
<class 'numpy.ndarray'>


In [20]:
#Operations on arrays
prices_array / earnings_array #will divide each element one by one

array([18.49130435, 17.56873823, 22.93775934, 24.58544839, 11.14202335,
       23.70517928, 14.8011782 ])

# Subsetting elements from array

Similar to subsetting lists

In [22]:
earnings[1:2]
prices[0:5:2]

[170.12, 55.28, 171.81]

# Two Dimensional Arrays

Combine 2 arrays into one (Table)

In [33]:
stock_array = np.array([earnings,prices]) #2 dimension arrays
print(stock_array)
print(stock_array.shape) #Print dimension of arrays
print(stock_array.size) #Give total elements in the array

[[  9.2    5.31   2.41   5.91  15.42   2.51   6.79]
 [170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]]
(2, 7)
14


# Transpose Array

Changes columns to row and vice versa

In [26]:
stock_array_transpose = np.transpose(stock_array)
print(stock_array_transpose)

[[  9.2  170.12]
 [  5.31  93.29]
 [  2.41  55.28]
 [  5.91 145.3 ]
 [ 15.42 171.81]
 [  2.51  59.5 ]
 [  6.79 100.5 ]]


# Subsetting 2D Arrays

Array[[row_index,column_index]]
Example : Array[[1:,3]] 2nd row 3rd column

In [45]:
print(stock_array[1:,4])
print(stock_array[0,])

[171.81]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


# Calculating Array

In [53]:
prices_mean = np.mean(prices)
prices_std = np.std(prices)
print(prices_mean,prices_std)

113.6857142857143 45.51277932221513


## Create sequence number using np.arange()

To create range of number, use np.arange

In [56]:
#np.arange(start,stop,step) <-Argument
number_arange = np.arange(1,100,2)
print(number_arange)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


# Boolean Array

Subset array by using boolean

In [62]:
Boolean_array = (number_arange > 30) #Statement
print(Boolean_array) #check the number
print(number_arange[Boolean_array])

[False False False False False False False False False False False False
 False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77
 79 81 83 85 87 89 91 93 95 97 99]
